### ISSUE TITLE
Get Docker installed on 4 dungeon workstations

### ISSUE THREAD

**Issue by devshawn** [dstelljes/container-project#1]
I figure we can use issues to track progress on things we are working on.

**What's Needed**:
- [x] Pick 4 computers to have Docker installed on (I say 2 dev lab, 2 teaching lab)
- [x] Send e-mail to dungeon masters
- [x] Have DM's add us to docker group on those machines
- [x] See that Docker is added on the requested machines

**Why Docker Group**:
From what I've been reading and trying, there is no way to spin up docker without being apart of this docker group or root. Let me know if you can find a way around it.

**Comment by devshawn** [comment]
We are hoping to have them installed on these 4 machines:
- Bistromath
- Cobar
- Multivac
- Macross

**Comment by dstelljes** [comment]
Laverne says we're good to go. Checked Bistromath and everything looks fine.
