### ISSUE TITLE
Finish the presentation

### ISSUE THREAD

**Issue by dstelljes** [dstelljes/container-project#11]
- [x] virtual machines vs. containers (not virtualization vs. containers)
- [x] diagram VM and container (emphasize shared kernel/filesystem diffs)
- [x] add slide for system containers vs. app containers (LX[CD] are for system, Docker/rkt are for app)
- [x] split lab services and course stuff into different slides; diagram stuff?
- [x] mention what's up with images: registries store images; containers are instances of images with diffs on top
- [x] list of demos at end
- [x] appendix slide: picture of cactus
- [x] appendix slide: Kyle Hakala or Seth Meyers?
- [x] distributed research systems

**Comment by devshawn** [comment]
Presentation is done and presented.
