### ISSUE TITLE
Make Informational Write-up of our Background Findings

### ISSUE THREAD

**Issue by devshawn** [dstelljes/container-project#2]
By the end of Week 2, I would like to have a nice write-up in out GitBook of the following things, feel free to add more:
- [x] Containers vs Virtual Machines
- [x] Docker Information (what is it, how does it work, etc) (Docker-Information.md)
- [x] chroot information (maybe cover this as a step below containers... chroot -> container -> VM?)
- [x] LXC Information
- [x] Write up of spinning up containers in the dungeon on lab computers

**Comment by dstelljes** [comment]
Working on the LXC stuff now. Seems like spinning up containers in the Dungeon wouldn't be a whole lot different than elsewhere, but we can check that.

**Comment by devshawn** [comment]
That's true -- I was thinking more of a general guide on spinning up containers / useful commands for Docker, using the lab as an example.

**Comment by devshawn** [comment]
I'll write up a detailed guide on installing Docker later today and we can get close to finishing this issue.

**Comment by devshawn** [comment]
After thinking about it more, I don't think it makes sense for our book to have installation instructions as they are very OS-dependent and Docker / LXC / etc has already detailed instructions we can look at.
