### ISSUE TITLE
Links to LXC/LXD and Docker are broken in your ToC

### ISSUE THREAD

**Issue by NicMcPhee** [dstelljes/container-project#3]
The links in your ToC to the sections on Docker and LXC/LXD both are broken. Maybe you need to rebuild the book? Or just rebuild the ToC?

**Comment by dstelljes** [comment]
The build at https://dstelljes.github.io/container-project/ seems fine and links work in the Markdown preview on GitHub as well. Old version, maybe?

**Comment by devshawn** [comment]
It is working fine for me on my latest build, running with `gitbook serve`. Have the latest code?

**Comment by NicMcPhee** [comment]
It looks like it works fine – I just need to reload pages in my browser.
