### ISSUE TITLE
Consider making a blog for this project

### ISSUE THREAD

**Issue by NicMcPhee** [dstelljes/container-project#4]
Have you two considering making a lightweight blog around this project? At some level it might be kind of redundent since the content is all in the book, but more than a few books have started life as a blog, so it's not clear that this is a problem.

I'm definitely not "expecting" or "requiring" it, but if you were interested it would be a cool way to share (updates on) your work "as you go".

**Comment by devshawn** [comment]
I wouldn't be opposed to a blog and would support the idea. I think it would be useful to keep an easily readable, chronologically-ordered summary of our project. However, I feel like the git commit's (if we keep up with good commit messages) are quite similar to what we would be doing while posting on a blog, and a lot of the information would be redundant as you said (not a bad thing).

@dstelljes what do you think?

**Comment by dstelljes** [comment]
I'm not sure that any as-you-go musings from me would be any good... "So I then I was like 10 minutes into this video of the inside of a Japanese chair factory when I thought, 'Hey, that paragraph about virtual machines would be a lot less bad if...'"

It seems like anything topical and worth sharing could probably be shoved into the book somewhere, and any related reflection or aside could go in a comment or commit (standard one-line summary, other stuff below). I'd try to blog if we had one, but I don't have any strong feelings about it. Dumping tangential stuff onto a personal blog could also be an option—@devshawn, do you have one?

**Comment by devshawn** [comment]
Haha, agreed.

I don't have a personal blog per se, rather, a personal website at http://devshawn.com.

I wouldn't be opposed to setting up a blog for this, it wouldn't be too hard. But generating content that is intellectual and useful beyond what is being put into the book / commit messages / comments could prove a challenge. I'm fine with whatever, and would be willing to set up the blog as well if we choose to go for it.

**Comment by NicMcPhee** [comment]
I'd drop it actually. If neither of you is particularly keen, it's probably just a distraction. I was essentially thinking you could share the different sections of the book as blog posts as you write them, but it'll all end up in the book, so maybe that duplication doesn't really buy you anything.

**Comment by devshawn** [comment]
I think this can be closed then in favor of detailed commit messages / just putting everything in the book.
