### ISSUE TITLE
Container Management Systems

### ISSUE THREAD

**Issue by devshawn** [dstelljes/container-project#7]
Eventually, I'd like to look into container management systems (mainly for Docker as they are most popular)
- [x] [Docker Swarm](https://www.docker.com/products/docker-swarm): Native clustering capabilities to turn group of Docker engines into a single, virtual Docker Engine. Easy to scale applications
- [x] [Shipyard](http://shipyard-project.com/): Built on top of Docker Swarm, UI to manage Docker images, containers, resources, and more within the swarm system
- [ ] [Kubernetes](http://kubernetes.io): Open-source system developed by Google for automating deployment, scaling, and management of containerized applications
- [ ] [Docker UI](https://github.com/kevana/ui-for-docker): Web interface for working with Docker as a UI rather than command-line. Could be useful / easy to manage commonly used containers / deploying in a lab setting to multiple computers, worth looking into
- [x] [Rancher](http://rancher.com/): Minimalist system (and operating system!) designed solely for running Docker containers. Not necessary applicable in the lab but very cool nonetheless

Feel free to add any suggestions on other things to look into.

**Comment by dstelljes** [comment]
I tried out the community version of [Mist.io](https://mist.io/) and wasn't really impressed. The interface is pretty, but it's definitely geared toward managing resources across a bunch of different cloud environments. They also push creating a Mist.io account for a lot of things.

**Comment by devshawn** [comment]
Working on write-up for Shipyard -- I'm really liking it so far. I've got the write up (with images!) for the container section of Shipyard done. The rest will come next week.

**Comment by dstelljes** [comment]
Rancher is super easy, tomorrow I'll maybe try to write up something like what you did for Shipyard: http://docs.rancher.com/rancher/latest/en/quick-start-guide/

**Comment by devshawn** [comment]
For now, I am opting to not write a detailed guide on Docker Swarm and it's CLI. I think it is more useful to dive straight into CMS with web / user interfaces rather than messing around with creating swarms by hand, especially with the complications of the lab firewalls.

**Comment by devshawn** [comment]
Closing this as we looked into the ones we thought were most relevant.
