### ISSUE TITLE
Look into Mesos (and Mesosphere, and DC/OS)

### ISSUE THREAD

**Issue by dstelljes** [dstelljes/container-project#9]
[Apache Mesos](http://mesos.apache.org/) is a distributed kernel that powers [DC/OS](https://dcos.io/). [Marathon](https://mesosphere.github.io/marathon/) is an orchestration tool that looks neat.

This maybe has more to do with distributed systems than containers, but it might be a thing worth looking into for the lab.

**Comment by devshawn** [comment]
Closed -- too far from the directed study and we looked at a good amount of orchestration tools.
